language: python
os:
- linux
cache: pip
virtualenv:
  system_site_packages: false
python:
- '3.6'
install:
- pip install --ignore-installed -r requirements.txt
script: 'python3 getDiningMenu.py > diningmenus.json

'
deploy:
  provider: releases
  api_key:
    secure: NsPTCn5jAX0E1khtwtoAOgX7X79pw2lRZJQhKMm958VFBf8hm946QhMDHXuDJptx546s5xf5Y6i7ah4wFe7C2FD1w6DngMkvtQDd9sTv0uGjXc0csdPO5SXxxzdEsI1OpHJB97WQdEYOe7fheq3hB9KDEz5/a7uWpWUpgNSbsjFNFc2wzz57uzOugTXk5a0DdKW+0PkYOTUyqCDytPhftQHg802XfRx2YPbSoaPLi2VLAfaDys/kiHkdLL3bmhaZlKsdbgKs2SzCFmT7uDK/YDlFVI+NLBbG66T1xDjc4GdNJ6nh+ukrZHLRR3RJWD9ezwBL1NIg5mkMWeS/B3bmjFVyx14L5bfFM8qJtmPCvh1+MmwmAa8k3pcEILKm43BGmm0/uwCMnY62DTSxkxpF/JQhJMspjaoHELvaZrAZ2SyBht0XKX4puBuwYhE8f7xeXlsolWLcu4lP5Cn/9xILDdRp2EtXbRoYFnzKwCyMgoaPNekLA1EH+ILUyQhZAUR+ILjrugzNVIIelVOOaveKVzBvAGupber2WG9GfWv12212zLuCrqZ7OcY+bBkMVB9rOZXDMAuGk3QjQROtu6ZQea3kOCQ2bvzjwNcuTBLF9EEGXyMEWiC0MWmOkYzTEZGj9IhGZnesaNhFoYK9hH/0G3e+toL3ggwszH+lpUua9Oo=
  file: diningmenus.json
  on:
    repo: lyuwen/CUDiningMenus
