language: python

os:
  - linux

cache: pip

virtualenv:
  system_site_packages: false

python:
  - '3.6'

install:
  - pip install --ignore-installed -r requirements.txt

script: |
  python3 getDiningMenu.py > diningmenus.json

before_deploy:
  - git config --local user.name "lyuwen"
  - git config --local user.email "fulvwen@gmail.com"
  - git tag -f nightly

deploy:
  overwrite: true
  skip_cleanup: true
  provider: releases
  tag_name: nightly
  api_key:
    secure: F2MkUgxXhQ2B/yS+qjr+gjdqg3hO3ZDV+7Nvx3kmXDCnQxlk83kpWG1amjPiiTyhL/dlqmX4MTxtQy93wqtsjrzR+12GhpSX42/tZeYEchORGC8fpWR77jCRTPZOlwXP3WIjQPKrCCHMtqkc5i97+lTpLX8MXP06LZp86ptkFDcPV56mGlNNILveus3n9zbecEP26nuF1iGrivEKQyHT1CF8wS4VC0QosufV/68ttluw/835T0oNLxDsfoAKfdK8gtvcISA5pKY0QvtBQ2FBQ9OTmybk2kZ2aAxOgqibzUzswxNECZB7pC30seIc+GmJBLP7Exm/Thrs19souOZDBO27WDAmHvrkxZD/q7ES9W3OchgZF89i68o2heYjb2WG6oq40RIGT275QqyBqmZDyKcqQun9ZIRrEdq25hIsSDvYlbI1zx8ECY098NL6GKwCnDZBHb/6/C2Tn2+ta+xR4phfgBD+x6+ThksI+/vDgkgjfYwIT65pshNWbmZjFlbCAVCbU1y8bbYhaGIUPymE+nR9q3sq4boo+YcwJZd9Z1I5GdowaiFxolA3hcQJmobFqupPAyFnlYPtedoDm1kWbEHMlRPcU+7dokWs66UTGHUM+U2H6WKKAanlrJ3yFz+lTDQaH99DkrbQO7Pjw8bv4f6TBS4b6J7NlxIVt6BZ5z4=
  file: diningmenus.json
  on:
    repo: lyuwen/CUDiningMenus
